### ISSUE TITLE
Unable to get the correct output

### ISSUE THREAD

**Issue by Nerdyvedi** [ZPdesu/SEAN#3]
Hi,
Thanks a lot for uploading such a wonderful work.  I have been trying to test this model, Not sure what I am doing wrong.
I downloaded the test dataset and the checkpoints you have uploaded, I am sure the paths are correct for the test command. 
The reconstructed images that I am getting are almost same as the input images, I am really confused why.

[This](https://drive.google.com/drive/folders/1SIwMfQO6H_4wOxpiFTZ8OATuWo9elP2l?usp=sharing) is the link to the result I am getting.

**Comment by ZPdesu** [comment]
Your results is correct. The test.py provides the reconstruction results. If you want to generate different images using style codes, you should use the UI mode.
