### ISSUE TITLE
Wanna see code of computing metrics

### ISSUE THREAD

**Issue by TrickyGo** [ZPdesu/SEAN#4]
Thanks you for sharing your amazing work. I'm new to pytorch and find your code clean and tought me a lot.  I found no code of computing metrics such as SSIM/RMSE/PSNR/FID as mentioned in the paper and I wanna know how you implemented that. Would you please upload those code? Thanks! 
Also, I'm running training.py SO SLOWLY on a single nvidia 2080ti with batch_size of 2. It's like a few hours not even one epoch finished. Do you have any idea?

**Comment by ZPdesu** [comment]
For FID calculation, you can use this [repo](https://github.com/mseitzer/pytorch-fid). The implementation of metrics SSIM/RMSE/PSNR can be found in [scikit-image](https://scikit-image.org/) package.

Yes, the training is terribly slow. Here are my suggestions: 1. Implement the parallel codes to accelerate the training. 2.Buy more expensive GPUs e.g. V100 (￣３￣)

**Comment by TrickyGo** [comment]
Got it! Thanks a lot!
