### ISSUE TITLE
labels

### ISSUE THREAD

**Issue by JNash123** [ZPdesu/SEAN#47]
CelebA-HQ/test/labels

how can i get these labels? what did u use as labels?

**Comment by keishatsai** [comment]
@JNash123 
How do you get the labels? Have you managed to generate them?

**Comment by JNash123** [comment]
> @JNash123 How do you get the labels? Have you managed to generate them?

https://blog.csdn.net/weixin_44145782/article/details/123498429, i don't know if u can understand Chinese,  u can try, and then u can get CelebAMaskHQ-mask
