### ISSUE TITLE
where can I download Facades dataset?

### ISSUE THREAD

**Issue by Ha0Tang** [ZPdesu/SEAN#9]

**Comment by ZPdesu** [comment]
I have a repo called lsaa-dataset. You can download the facades datasets according to the instructions.

**Comment by ZPdesu** [comment]
I am not sure whether we can directly publish these images, since they are collected from Google Street View.  Therefore, we provided the download scripts from where you can get these images by yourself. 
I understand the whole process is painful........

**Comment by Ha0Tang** [comment]
Thanks.
